PLANT_NAME_MAP = {
    "ATO2 Wastewater Treatment Plant": "Rome",
    "Budapesti Kozponti Szennyviztisztito Telep": "Budapest",
    "Dokhaven": "Rotterdam",
    "Gruppo HERA": "Bologna",
    "Rensningsanlaeg Avedoere": "Copenhagen_RA",
    "Rensningsanlaeg Damhusaaen": "Copenhagen_RD",
    "Rensningsanlaeg Lynetten": "Copenhagen_RL",
}

ORDER_COLOR_MAP = {
    "Unassigned":     "#000000",
    "Crassvirales":    "#0072B2",
    "Timlovirales":    "#E69F00",
    "Chitovirales":    "#009E73",
    "Imitervirales":   "#D55E00",
    "Herpesvirales":   "#CC79A7",
    "Lefavirales":     "#F0E442",
    "Bunyavirales":    "#999999",
    "Pimascovirales":  "#7F7F7F",
    "Algavirales":     "#A6761D",
    "Halopanivirales": "#1B9E77",
    "Mononegavirales": "#7570B3",
    "Rowavirales":     "#E7298A",
    "Picornavirales":  "#66A61E",
    "Tubulavirales":   "#A6CEE3",
    "Unassigned":      "#AAAAAA",
    "Other":           "#DDDDDD",
}

FAMILY_COLOR_MAP = {
    "Crevaviridae":    "#a6cee3",
    "Herelleviridae":  "#1f78b4",
    "Intestiviridae":  "#b2df8a",
    "Kyanoviridae":    "#33a02c",
    "Mimiviridae":     "#fb9a99",
    "Peduoviridae":    "#e31a1c",
    "Schitoviridae":   "#fdbf6f",
    "Steigviridae":    "#ff7f00",
    "Steitzviridae":   "#cab2d6",
    "Straboviridae":   "#6a3d9a",
    "Suoliviridae":    "#ffff99",
    "Unassigned":      "#AAAAAA",
    "Other":           "#DDDDDD",

    "Demerecviridae":  "#8dd3c7",
    "Autographiviridae":"#ffffb3",
    "Poxviridae":      "#bebada",
    "Arenbergviridae": "#fb8072",
}

GENUS_COLOR_MAP = {
    "Unassigned":        "#AAAAAA",
    "Other":             "#DDDDDD",
    "Carjivirus":        "#e31a1c",
    "Burzaovirus":       "#1f78b4",
    "Punavirus":         "#33a02c",
    "Agtrevirus":        "#ff7f00",
    "Betabaculovirus":   "#6a3d9a",
    "Gihfavirus":        "#a6cee3",
    "Casadabanvirus":    "#fb9a99",
    "Purivirus":         "#b2df8a",
    "Baikalvirus":       "#cab2d6",
    "Pamexvirus":        "#fdbf6f",
    "Immutovirus":       "#ffff99",
}
